-- ShowroomCiro — Funciones y vistas de lógica de negocio
-- Basado en docs/design.md (sección 2, "APIs principales"), docs/prd.md ("Reportes") y
-- docs/tasks.md (Módulo 2). Requiere 0001_init_schema.sql y 0002_rls_policies.sql ya aplicadas.
--
-- Contenido:
--   0. Ajustes de schema: se quita `cuentas.estado`, se agrega `ventas.caja_id` y
--      `productos.codigo`.
--   1. Helpers de fecha local (Argentina).
--   2. Trigger BEFORE INSERT en `variantes` que genera el SKU automáticamente.
--   3. Función RPC `cerrar_caja(caja_id, monto_contado)`.
--   4. Vista `cuentas_vista` con saldo y estado calculados al vuelo.
--   5. Reportes (solo Dueño/a): `reportes_ventas_vista`, `reportes_top_productos_vista`,
--      `reportes_cuentas_pendientes_vista` y RPCs para rangos de fechas arbitrarios.
--
-- Zona horaria: Supabase corre en UTC. Todo lo que dependa de "hoy" o de agrupar por día
-- se calcula con la hora de Argentina; si no, a partir de las 21:00 locales CURRENT_DATE ya
-- es "mañana" (una cuenta pasaría a vencida 3 h antes y las ventas de la noche caerían en
-- el día siguiente).

-- ============================================================================
-- 0. Ajustes de schema
-- ============================================================================

-- cuentas.estado ya no se guarda: `cuentas_vista` es la única fuente de verdad del estado.
alter table public.cuentas drop constraint if exists chk_cuentas_estado;
alter table public.cuentas drop column if exists estado;

-- Cada venta queda vinculada a la caja que estaba abierta cuando se hizo.
-- NOT NULL sin default: si `ventas` ya tuviera filas cargadas a mano, este ALTER falla
-- (hay que asignarles una caja o borrarlas antes). El seed no carga ventas.
alter table public.ventas
  add column caja_id uuid not null references public.cajas (id);

create index idx_ventas_caja_id on public.ventas (caja_id);

-- Número correlativo legible del producto (1, 2, 3...), usado en el SKU (SC-001-...).
-- `productos.id` sigue siendo el uuid y la PK; `codigo` es solo un identificador humano.
-- "by default" permite cargar un código a mano si hiciera falta (ej. migrar datos viejos).
alter table public.productos
  add column codigo integer generated by default as identity;

alter table public.productos
  add constraint uq_productos_codigo unique (codigo);

-- ============================================================================
-- 1. Helpers de fecha local
-- ============================================================================

create or replace function public.fecha_local(p_momento timestamptz)
returns date
language sql
stable
as $$
  select (p_momento at time zone 'America/Argentina/Buenos_Aires')::date;
$$;

create or replace function public.hoy_local()
returns date
language sql
stable
as $$
  select public.fecha_local(now());
$$;

-- ============================================================================
-- 2. Generación automática de SKU en variantes
-- ============================================================================
-- Formato: SC-<codigo producto, mín. 3 dígitos>-<color abreviado>-<talle>
-- Ejemplo: producto 1, Azul, M  ->  SC-001-AZ-M
--
-- - Código de producto: `productos.codigo` con padding a 3 dígitos. Desde el producto
--   1000 usa los dígitos que haga falta (SC-1000-...), nunca se trunca.
-- - Color abreviado (2-3 letras):
--     · una palabra: primera letra + primera consonante siguiente
--       (Azul -> AZ, Negro -> NG, Rojo -> RJ, Blanco -> BL).
--     · varias palabras: iniciales de las primeras 3 (Verde Oliva -> VO, Azul Marino -> AM).
-- - Talle: en mayúsculas, solo letras y números (M, XL, 38, UNICO).
-- - Unicidad: si el SKU base ya existe (ej. Negro y Nogal abrevian igual: NG), se agrega
--   un sufijo numérico: SC-001-NG-M-2, SC-001-NG-M-3...
--
-- Solo actúa si `sku` viene null o vacío; si la app manda un SKU explícito, se respeta.

create or replace function public.normalizar_texto_sku(p_texto text)
returns text
language sql
immutable
as $$
  -- Mayúsculas, sin tildes/diéresis/ñ, solo letras, números y espacios simples.
  select btrim(regexp_replace(
    regexp_replace(
      translate(
        upper(coalesce(p_texto, '')),
        'ÁÉÍÓÚÀÈÌÒÙÄËÏÖÜÂÊÎÔÛÑÇ',
        'AEIOUAEIOUAEIOUAEIOUNC'
      ),
      '[^A-Z0-9 ]', '', 'g'
    ),
    '\s+', ' ', 'g'
  ));
$$;

create or replace function public.abreviar_color_sku(p_color text)
returns text
language plpgsql
immutable
as $$
declare
  v_color    text := public.normalizar_texto_sku(p_color);
  v_palabras text[];
  v_abrev    text := '';
  i          integer;
begin
  if v_color = '' then
    return 'XX';
  end if;

  v_palabras := string_to_array(v_color, ' ');

  if array_length(v_palabras, 1) >= 2 then
    for i in 1 .. least(array_length(v_palabras, 1), 3) loop
      v_abrev := v_abrev || left(v_palabras[i], 1);
    end loop;
    return v_abrev;
  end if;

  return left(v_color, 1)
    || coalesce(
         substring(substr(v_color, 2) from '[B-DF-HJ-NP-TV-Z]'),
         nullif(substr(v_color, 2, 1), ''),
         'X'
       );
end;
$$;

create or replace function public.generar_sku_variante()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_codigo   integer;
  v_talle    text;
  v_sku_base text;
  v_sku      text;
  v_sufijo   integer := 1;
begin
  if new.sku is not null and btrim(new.sku) <> '' then
    return new;
  end if;

  select codigo
  into v_codigo
  from public.productos
  where id = new.producto_id;

  if v_codigo is null then
    raise exception 'No se puede generar el SKU: el producto % no existe', new.producto_id;
  end if;

  v_talle := replace(public.normalizar_texto_sku(new.talle), ' ', '');
  if v_talle = '' then
    v_talle := 'U';
  end if;

  v_sku_base := 'SC-'
    || lpad(v_codigo::text, greatest(3, length(v_codigo::text)), '0')
    || '-' || public.abreviar_color_sku(new.color)
    || '-' || v_talle;

  -- Serializa la generación por SKU base: dos inserts concurrentes que colisionan (ej.
  -- Negro y Nogal en el mismo talle) no pueden elegir el mismo sufijo. El lock se libera
  -- al terminar la transacción.
  perform pg_advisory_xact_lock(hashtext('sku:' || v_sku_base));

  v_sku := v_sku_base;
  while exists (select 1 from public.variantes where sku = v_sku) loop
    v_sufijo := v_sufijo + 1;
    v_sku := v_sku_base || '-' || v_sufijo;
  end loop;

  new.sku := v_sku;
  return new;
end;
$$;

create trigger trg_variantes_generar_sku
  before insert on public.variantes
  for each row
  execute function public.generar_sku_variante();

-- ============================================================================
-- 3. RPC cerrar_caja
-- ============================================================================
-- Uso desde el frontend: supabase.rpc('cerrar_caja', { caja_id, monto_contado })
-- Devuelve la fila de `cajas` ya cerrada (con monto_esperado y diferencia) para que la
-- pantalla "Caja — Cierre" pueda mostrar el resultado antes del logout automático.
--
-- monto_esperado = monto_inicial + suma de ventas.total EN EFECTIVO de esta caja
--                  (ventas.caja_id = caja_id, es decir, todas las hechas desde la apertura).
-- diferencia     = monto_contado - monto_esperado (negativo = falta plata).
--
-- Decisión sobre medio de pago: tasks.md dice "suma de ventas desde la apertura" sin
-- discriminar, pero `monto_contado` es el conteo de efectivo físico del cajón
-- (requirements/design: "conteo de efectivo físico"). Tarjeta y transferencia nunca
-- entran al cajón, así que sumarlas generaría una "diferencia" falsa. Si en algún momento
-- se quiere un cierre por todos los medios, habría que contar/declarar cada medio aparte.
--
-- security definer: permite sumar ventas sin depender de lo que el rol del usuario pueda
-- leer. Por eso valida explícitamente que quien llama sea un usuario activo de la app.
--
-- Los parámetros se llaman igual que columnas (caja_id, monto_contado) porque así los
-- nombra la API pública; dentro del cuerpo se referencian siempre como
-- `cerrar_caja.caja_id` / `cerrar_caja.monto_contado` para evitar ambigüedad.

create or replace function public.cerrar_caja(caja_id uuid, monto_contado numeric)
returns public.cajas
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usuario_id     uuid := auth.uid();
  v_caja           public.cajas;
  v_total_efectivo numeric(10, 2);
  v_monto_esperado numeric(10, 2);
begin
  if v_usuario_id is null or public.rol_actual() is null then
    raise exception 'Usuario no autenticado o inactivo'
      using errcode = '42501';
  end if;

  if cerrar_caja.monto_contado is null or cerrar_caja.monto_contado < 0 then
    raise exception 'El monto contado debe ser un número mayor o igual a 0'
      using errcode = '22023';
  end if;

  -- Bloquea la fila para evitar dos cierres simultáneos de la misma caja.
  select c.*
  into v_caja
  from public.cajas c
  where c.id = cerrar_caja.caja_id
  for update;

  if not found then
    raise exception 'La caja % no existe', cerrar_caja.caja_id
      using errcode = 'P0002';
  end if;

  if v_caja.fecha_cierre is not null then
    raise exception 'La caja ya fue cerrada el %', v_caja.fecha_cierre
      using errcode = '22023';
  end if;

  select coalesce(sum(v.total), 0)
  into v_total_efectivo
  from public.ventas v
  where v.caja_id = cerrar_caja.caja_id
    and v.medio_pago = 'efectivo';

  v_monto_esperado := v_caja.monto_inicial + v_total_efectivo;

  update public.cajas c
  set monto_esperado    = v_monto_esperado,
      monto_contado     = cerrar_caja.monto_contado,
      diferencia        = cerrar_caja.monto_contado - v_monto_esperado,
      fecha_cierre      = now(),
      usuario_cierre_id = v_usuario_id
  where c.id = cerrar_caja.caja_id
  returning c.* into v_caja;

  return v_caja;
end;
$$;

revoke execute on function public.cerrar_caja(uuid, numeric) from public, anon;
grant execute on function public.cerrar_caja(uuid, numeric) to authenticated;

-- ============================================================================
-- 4. Vista cuentas_vista
-- ============================================================================
-- La consultan Cuentas (Módulo 7) y el panel de Alertas del Dashboard (Módulo 4):
-- no cambiar el nombre ni quitar columnas sin revisar esos módulos.
--
-- Expone todas las columnas de `cuentas` más:
--   - total_pagado: suma de cuenta_pagos.
--   - saldo:        monto_total - total_pagado.
--   - estado:       'pagado'     si saldo <= 0
--                   'vencido'    si fecha_limite < hoy
--                   'por_vencer' si fecha_limite está entre hoy y hoy + N días
--                   'al_dia'     en cualquier otro caso
--
-- security_invoker: la vista respeta el RLS de `cuentas` y `cuenta_pagos` del usuario
-- que consulta (sin esto correría con los permisos del dueño de la vista y saltearía RLS).

create or replace view public.cuentas_vista
with (security_invoker = true)
as
with parametros as (
  select
    public.hoy_local() as hoy,
    -- Días de anticipación para marcar una cuenta como 'por_vencer'. Cambiar acá.
    3 as dias_aviso_por_vencer
),
pagos as (
  select cp.cuenta_id, sum(cp.monto) as total_pagado
  from public.cuenta_pagos cp
  group by cp.cuenta_id
),
base as (
  select
    c.id,
    c.cliente_nombre,
    c.cliente_telefono,
    c.monto_total,
    c.fecha_limite,
    c.created_at,
    coalesce(p.total_pagado, 0)::numeric(10, 2)                 as total_pagado,
    (c.monto_total - coalesce(p.total_pagado, 0))::numeric(10, 2) as saldo
  from public.cuentas c
  left join pagos p on p.cuenta_id = c.id
)
select
  b.id,
  b.cliente_nombre,
  b.cliente_telefono,
  b.monto_total,
  b.fecha_limite,
  b.created_at,
  b.total_pagado,
  b.saldo,
  case
    when b.saldo <= 0 then 'pagado'
    when b.fecha_limite < pr.hoy then 'vencido'
    when b.fecha_limite <= pr.hoy + pr.dias_aviso_por_vencer then 'por_vencer'
    else 'al_dia'
  end as estado
from base b
cross join parametros pr;

comment on view public.cuentas_vista is
  'Cuentas con total_pagado, saldo y estado (al_dia/por_vencer/vencido/pagado) calculados al vuelo.';

grant select on public.cuentas_vista to authenticated;

-- ============================================================================
-- 5. Reportes (solo Dueño/a)
-- ============================================================================
-- Métricas según docs/prd.md ("Reportes"):
--   - Ventas del día, la semana y el mes: cantidad de ventas y total vendido.
--   - Productos más vendidos en un período: por unidades vendidas.
--   - Ticket promedio del período = total vendido ÷ cantidad de ventas.
--   - Total adeudado en cuentas pendientes y cuántas están por vencer.
--
-- Todas las ventas cuentan, sin importar el medio de pago. Los días se toman en hora
-- de Argentina; la semana empieza el lunes (ISO, lo que usa date_trunc('week')).
--
-- Permisos: el Vendedor puede leer `ventas` (lo necesita el POS, ver 0002), así que el
-- RLS de las tablas no alcanza para ocultarle los reportes. Las vistas filtran con
-- `public.es_dueno()`: para el Vendedor devuelven 0 filas (o ceros en el resumen de
-- cuentas). Las RPCs de rango directamente rechazan la llamada.

-- 5.1 Ventas por período ------------------------------------------------------
-- Una fila por (periodo, fecha_inicio). Ej. desde el frontend:
--   from('reportes_ventas_vista').select('*').eq('periodo', 'mes').eq('fecha_inicio', '2026-09-01')

create or replace view public.reportes_ventas_vista
with (security_invoker = true)
as
with ventas_locales as (
  select v.total, public.fecha_local(v.fecha) as dia
  from public.ventas v
  where public.es_dueno()
),
por_periodo as (
  select 'dia'::text as periodo, vl.dia as fecha_inicio, vl.total
  from ventas_locales vl
  union all
  select 'semana', date_trunc('week', vl.dia::timestamp)::date, vl.total
  from ventas_locales vl
  union all
  select 'mes', date_trunc('month', vl.dia::timestamp)::date, vl.total
  from ventas_locales vl
)
select
  pp.periodo,
  pp.fecha_inicio,
  count(*)::integer                              as cantidad_ventas,
  sum(pp.total)::numeric(12, 2)                  as total_vendido,
  round(sum(pp.total) / count(*), 2)::numeric(12, 2) as ticket_promedio
from por_periodo pp
group by pp.periodo, pp.fecha_inicio;

comment on view public.reportes_ventas_vista is
  'Ventas agrupadas por periodo (dia/semana/mes): cantidad, total y ticket promedio. Solo Dueño/a.';

grant select on public.reportes_ventas_vista to authenticated;

-- 5.2 Top productos por período -------------------------------------------------
-- Una fila por (periodo, fecha_inicio, producto). `ranking` = posición dentro del
-- período (1 = más vendido, por unidades y luego por monto). Ej. top 5 del mes:
--   .eq('periodo', 'mes').eq('fecha_inicio', '2026-09-01').lte('ranking', 5).order('ranking')

create or replace view public.reportes_top_productos_vista
with (security_invoker = true)
as
with items as (
  select
    va.producto_id,
    vi.cantidad,
    vi.cantidad * vi.precio_unitario as subtotal,
    public.fecha_local(v.fecha)      as dia
  from public.venta_items vi
  join public.ventas v    on v.id = vi.venta_id
  join public.variantes va on va.id = vi.variante_id
  where public.es_dueno()
),
por_periodo as (
  select 'dia'::text as periodo, i.dia as fecha_inicio, i.producto_id, i.cantidad, i.subtotal
  from items i
  union all
  select 'semana', date_trunc('week', i.dia::timestamp)::date, i.producto_id, i.cantidad, i.subtotal
  from items i
  union all
  select 'mes', date_trunc('month', i.dia::timestamp)::date, i.producto_id, i.cantidad, i.subtotal
  from items i
),
agregado as (
  select
    pp.periodo,
    pp.fecha_inicio,
    pp.producto_id,
    sum(pp.cantidad)::integer        as unidades_vendidas,
    sum(pp.subtotal)::numeric(12, 2) as total_vendido
  from por_periodo pp
  group by pp.periodo, pp.fecha_inicio, pp.producto_id
)
select
  a.periodo,
  a.fecha_inicio,
  a.producto_id,
  p.codigo   as producto_codigo,
  p.nombre   as producto_nombre,
  p.foto_url,
  a.unidades_vendidas,
  a.total_vendido,
  rank() over (
    partition by a.periodo, a.fecha_inicio
    order by a.unidades_vendidas desc, a.total_vendido desc
  )::integer as ranking
from agregado a
join public.productos p on p.id = a.producto_id;

comment on view public.reportes_top_productos_vista is
  'Productos vendidos por periodo (dia/semana/mes) con unidades, total y ranking. Solo Dueño/a.';

grant select on public.reportes_top_productos_vista to authenticated;

-- 5.3 Cuentas pendientes ---------------------------------------------------------
-- Siempre devuelve exactamente una fila (con ceros si no hay cuentas o si no es Dueño/a).
-- Se apoya en cuentas_vista, así que usa la misma definición de estado y de "por vencer".

create or replace view public.reportes_cuentas_pendientes_vista
with (security_invoker = true)
as
select
  coalesce(sum(cv.saldo), 0)::numeric(12, 2)                   as total_adeudado,
  count(*)::integer                                            as cantidad_pendientes,
  count(*) filter (where cv.estado = 'por_vencer')::integer    as cantidad_por_vencer,
  count(*) filter (where cv.estado = 'vencido')::integer       as cantidad_vencidas
from public.cuentas_vista cv
where cv.estado <> 'pagado'
  and public.es_dueno();

comment on view public.reportes_cuentas_pendientes_vista is
  'Resumen de cuentas con saldo pendiente: total adeudado, cantidad, por vencer y vencidas. Solo Dueño/a.';

grant select on public.reportes_cuentas_pendientes_vista to authenticated;

-- 5.4 RPCs para un rango de fechas arbitrario ---------------------------------------
-- Para cuando la pantalla de Reportes necesite un período que no sea día/semana/mes
-- calendario (ej. "últimos 7 días"). `desde` y `hasta` son fechas locales, inclusive.
--   supabase.rpc('reporte_ventas_rango', { desde: '2026-09-01', hasta: '2026-09-26' })
--   supabase.rpc('reporte_top_productos_rango', { desde, hasta, limite: 5 })

create or replace function public.reporte_ventas_rango(desde date, hasta date)
returns table (
  cantidad_ventas integer,
  total_vendido   numeric(12, 2),
  ticket_promedio numeric(12, 2)
)
language plpgsql
stable
set search_path = public
as $$
begin
  if not coalesce(public.es_dueno(), false) then
    raise exception 'Solo el Dueño/a puede ver reportes'
      using errcode = '42501';
  end if;

  return query
  select
    count(*)::integer,
    coalesce(sum(v.total), 0)::numeric(12, 2),
    coalesce(round(sum(v.total) / nullif(count(*), 0), 2), 0)::numeric(12, 2)
  from public.ventas v
  where public.fecha_local(v.fecha) between desde and hasta;
end;
$$;

create or replace function public.reporte_top_productos_rango(desde date, hasta date, limite integer default 10)
returns table (
  producto_id       uuid,
  producto_codigo   integer,
  producto_nombre   text,
  foto_url          text,
  unidades_vendidas integer,
  total_vendido     numeric(12, 2),
  ranking           integer
)
language plpgsql
stable
set search_path = public
as $$
begin
  if not coalesce(public.es_dueno(), false) then
    raise exception 'Solo el Dueño/a puede ver reportes'
      using errcode = '42501';
  end if;

  return query
  with agregado as (
    select
      va.producto_id                                   as prod_id,
      sum(vi.cantidad)::integer                        as unidades,
      sum(vi.cantidad * vi.precio_unitario)::numeric(12, 2) as total
    from public.venta_items vi
    join public.ventas v     on v.id = vi.venta_id
    join public.variantes va on va.id = vi.variante_id
    where public.fecha_local(v.fecha) between desde and hasta
    group by va.producto_id
  ),
  rankeado as (
    select
      a.prod_id,
      p.codigo,
      p.nombre,
      p.foto_url  as foto,
      a.unidades,
      a.total,
      rank() over (order by a.unidades desc, a.total desc)::integer as pos
    from agregado a
    join public.productos p on p.id = a.prod_id
  )
  select r.prod_id, r.codigo, r.nombre, r.foto, r.unidades, r.total, r.pos
  from rankeado r
  where r.pos <= limite
  order by r.pos;
end;
$$;

revoke execute on function public.reporte_ventas_rango(date, date) from public, anon;
grant execute on function public.reporte_ventas_rango(date, date) to authenticated;
revoke execute on function public.reporte_top_productos_rango(date, date, integer) from public, anon;
grant execute on function public.reporte_top_productos_rango(date, date, integer) to authenticated;
